version: '3'
volumes:
  bundle:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bundle:/usr/local/bundle
      - ~/.aws:/root/.aws
      - ./src:/usr/local/app:delegated
    stdin_open: true
    tty: true
