version: '3'
volumes:
  bundle:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bundle:/usr/local/app/vendor/bundle
      - ~/.aws:/root/.aws
      - .:/usr/local/app:delegated
    stdin_open: true
    tty: true
