AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my scraping service

Resources:
  ScrapingService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: MoneyFowardScrapingService
      Handler: money_forward.MoneyForward.handler
      Runtime: ruby2.5
      Timeout: 30
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
